### PR TITLE
feat: use bitwsise xor operations for getting orientation

### PR DESCRIPTION
**Pull request by lavafroth**
### Changes
- Represent `Orientation` as enum with 4 primary variants plus an `Auto` variant
- The underlying type is a `u8` (one byte)
- Use the `u8` representation when not displaying the orientation because one byte is inexpensive
- Since a strand can be forward or reverse, we represent the boolean values as `1` and `0` (`u8`) so that we can later use them for faster bitwise operations
- The `HashMap`s with the keys of type `Orientation` are now represented as vectors with a maximum of 5 elements, each corresponding to a variant of `Orientation`

### CODE REVIEW

**Comment by rrwick** [comment]
Thanks for this! However, the formatting changes make it difficult for me to see exactly what has changed...

Have you profiled this code, before and after the change? If so, how much of a performance improvement did it make? If it's a significant improvement, then I'd be interested in merging this PR and would ask if you could remove the formatting changes. But if it's a small difference, then I'm okay with leaving orientations as strings, even if that's less efficient.

**Comment by lavafroth** [comment]
Sure, I will remove the formatting changes and share the benchmarks.

**Comment by lavafroth** [comment]
# Benchmarks

Benchmarks are performed using [hyperfine](https://github.com/sharkdp/hyperfine) on 1 million runs of respective test functions. This was done by compiling a binary in release mode that only ran the specific test function.

## `test_get_orientation`

Current implementation:

```
Time (mean ± σ):      8.212 s ±  0.075 s    [User: 8.180 s, System: 0.004 s]
Range (min … max):    8.108 s …  8.335 s    10 runs
```

PR implementation:

```
Time (mean ± σ):      7.892 s ±  0.116 s    [User: 7.863 s, System: 0.003 s]
Range (min … max):    7.811 s …  8.200 s    10 runs
```

## `test_auto_determine_orientation`

Current implementation:

```
Time (mean ± σ):      2.196 s ±  0.018 s    [User: 2.185 s, System: 0.001 s]
Range (min … max):    2.170 s …  2.226 s    10 runs
```

PR implementation:

```
Time (mean ± σ):     499.9 ms ±   9.1 ms    [User: 496.4 ms, System: 1.2 ms]
Range (min … max):   488.4 ms … 520.1 ms    10 runs
```

**Comment by rrwick** [comment]
Thank you for doing the formatting changes!

I tried this out and found a bug: the `auto_determine_orientation` function was returning `Orientation::Auto` when it should have been returning the best possible orientation, and this caused Polypolish to fail. I think I've fixed this, and I've also changed an inequality in `get_orientation` to make sure that the new code produces results identical to the old code.

I then ran some benchmarks on a full run of `polypolish filter`, but I saw essentially no improvement 😢 While your benchmarks show that the `auto_determine_orientation` is much faster, that function is only called once. Also, the bitwise operations, while efficient, make the code harder for me to understand.

Since this new implementation adds about 75 lines of code and doesn't seem to help performance, I'm going to opt against merging - sorry! I do appreciate your work on it, though.

**Comment by lavafroth** [comment]
Sure thing. Thank you very much for taking the time to review this PR!

**Pull request closed without merging**
